settingVersions:
  recommendedSettingsVersion: 'default'
  recommendedSettingsLabels: ['default', 'simulation']

setting:
  default:
    type: 'lsst'
    configuration:
      host: 'localhost'  # IP of the weather station
      port: 50000
      buffer_size: 2048
      simulation: False
  simulation:
    type: 'lsst'
    configuration:
      host: 'localhost'  # IP of the weather station
      port: 50000
      buffer_size: 2048
      simulation: True
